apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.10.0
          ports:
            - containerPort: 5044
          env:
            - name: ELASTICSEARCH_HOST
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: logrotate-config
              mountPath: /etc/logrotate.d/logstash
              subPath: logstash-logrotate.conf
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logrotate-config
          configMap:
            name: logstash-logrotate-config
